### ISSUE TITLE
Refreshing the Webpage with a Conversation Open Will Result in Messages Getting Flagged

### ISSUE THREAD

**Issue by Stratocaster22** [4as/ChatGPT-DeMod#17] opened 2023-05-29 21:48 UTC
This extension works great. I've used it via mobile and desktop with great success. However, I've recently noticed (not sure if a GPT update did this...) that if you have a conversation window open and you refresh the webpage (necessary sometimes when it hangs or there's an error) then upon the conversation reloading, many messages show up as flagged with the dreaded _"This content may violate our [content policy](https://platform.openai.com/docs/usage-policies/content-policy). If you believe this to be in error, please [submit your feedback](https://forms.gle/3gyAMj5r5rTEcgbs5) — your input will aid our research in this area."_

Any thoughts on this?

**Comment by 4as** [comment] 2023-05-30 10:19
I'm not sure if I understand. If you refresh your conversation, all messages that were already flagged for moderation will remained flagged after refresh, there is no going back. Unless you mean that refreshing will cause all messages being flagged? In which case I didn't observe that behavior. Can you provide details on how to reproduce that behavior? And on what browser are you? Also what version of DeMod are you using?

**Comment by Stratocaster22** [comment] 2023-05-31 03:19
Yes, refreshing will CAUSE the messages to be flagged. Messages that were previously unflagged will be flagged upon webpage refresh...it's very odd. You can load in and out of the conversation without issue, but if you are in a specific conversation and hit webpage refresh, that's where the error arises.

To reproduce I would create a conversation that has wording/phrases/content that would typically be flagged, get several message/replies in and then hit refresh within your browser. 

I'm using Chrome Version 113.0.5672.92 (Official Build) (arm64). 

I'm using DeMod version 1.8.

**Comment by 4as** [comment] 2023-06-02 00:09
I see now what you were talking about. OpenAI has apparently been rolling out a new feature that allows people to share their conversations. If you access the conversation directly (like use the URL or... refresh it - it is the same thing) it is now being checked internally on their servers. Since the check is internal there is no way to workaround it.
I'm going to see if DeMod could be used to block or redirect any attempts at accessing a conversation directly through the URL.

**Comment by 4as** [comment] 2023-06-03 16:57
I just pushed an update that will redirect any attempts at refreshing or accessing the conversation directly back to the "new chat" page.

**Closed by 4as** 2023-06-03 16:57 UTC

**Comment by Stratocaster22** [comment] 2023-06-03 19:26
That’s awesome you got this fixed so fast! Props to you!

Cheers! Great work!
