### ISSUE TITLE
'Unexpected end of JSON input' when DeMod is active.

### ISSUE THREAD

**Issue by sschroeder59** [4as/ChatGPT-DeMod#38] opened 2024-01-04 01:03 UTC
![image](https://github.com/4as/ChatGPT-DeMod/assets/73884269/ff9e98d8-ae10-42e1-8770-ac79c7ecd0a5)

Only occurs when its on. Anyone else experiencing this?

**Comment by 4as** [comment] 2024-01-04 17:41
Is that ChatGPT4? I don't have access to it so I can't verify what is wrong, however ChatGPT3.5 seems to work fine for me at this moment. Can you verify whether the issue is with ChatGPT4, 3.5, or both?

**Comment by sschroeder59** [comment] 2024-01-05 10:59
Oops, thanks for pointing that out. I usually use ChatGPT-4. I just now tried 3.5 though, same issue, exact same result.

**Comment by sschroeder59** [comment] 2024-01-05 11:14
Addendum: What's really interesting is if I reload the page later, it shows the response, both in the case of ChatGPT-3.5 and 4. It won't work at the time, but (SOMETIMES) it shows up later. :/ Confusing.

**Comment by 4as** [comment] 2024-01-05 13:31
So far everything for me is in order, which means they might be rolling out new changes. Usually some changes are not instantly available to, for example, Europeans, even tho they released them in US.
Anyway, JSON error indicates that they changed something in the format the messages are arriving. I'll need to know what is it before I can fix it. Which means you'll have to wait until they make their changes available to me too.  
In the mean time you can try different browser to be sure it's nothing on your end.
Or, if you know what you're doing, you could also send me the JSON response that ChatGPT is sending and I could try fixing the format based on that.

**Comment by sschroeder59** [comment] 2024-01-06 14:38
I've never tried using Tampermonkey on anything but Chrome, not even sure which browser would be a good alternative. ^^; I'm definitely in the category of 'barely knows what they're doing'.

I've tried removing the extension and script and reinstalling both just to try -that- option, but the same error occurs. I'll keep checking on here, thanks for taking the time to respond! :)

**Comment by e39a562r** [comment] 2024-01-12 10:34
I'm getting same error message since yesterday.
![image](https://github.com/4as/ChatGPT-DeMod/assets/1002511/19c7d8b6-d0e6-4303-9581-78713af0b454)

Seems they are really rolling out new version to more user.

**Comment by e39a562r** [comment] 2024-01-13 14:09
While I preparing the patch, I encounter 3 bugs from OpenAI themselves, so...
I guess we probably are using a beta branch and they probably will update their code again soon.

**Comment by OMGitsMatt45** [comment] 2024-01-20 19:19
Happened to me too. Just put in an official bug report about it

**Comment by OMGitsMatt45** [comment] 2024-01-23 02:15
When do you think the ChatGPT update would finally drop?

**Comment by OMGitsMatt45** [comment] 2024-01-23 02:23
HOLY SHIT IT'S FINALLY GONE NOW! I think we can close this as an issue but 4as you might want to take a look and see if anything's changed.

**Comment by e39a562r** [comment] 2024-01-23 11:22
It's gone for me too. I'll close the PR.

**Comment by 4as** [comment] 2024-01-23 18:27
That's a bit unexpected. I'll leave the issue open just in case they rolled back the changes temporarily. They might have been just testing something and real update will be coming up later.

**Comment by KDLGates** [comment] 2024-02-01 20:53
I don't have much more to add except this same `Unexpected end of JSON input` error started occurring for me today. I hadn't seen it before, and now it's consistent when running with the currently updated Tampermonkey install of DeMod. Also running on GPT-4 with a custom GPT.

**Comment by ShionArtist** [comment] 2024-02-02 03:38
![m 3](https://github.com/4as/ChatGPT-DeMod/assets/13771413/6fd0f49c-4705-457e-aa37-b9702326d511)

so the error came up around today with demod disabled via grease monkey cchatgpt works

**Comment by OMGitsMatt45** [comment] 2024-02-02 04:02
happy to me again today

**Comment by Chad-RK** [comment] 2024-02-02 07:18
Disabling uBlock Origin simply gave me a few normal JavaScript errors that just reiterated the problem of "unexpected end of JSON input". Possible they changed how the API returns certain things on the backend?

**Comment by sunnys1d3** [comment] 2024-02-02 16:56
@e39a562r's patch works.

**Comment by Agooro** [comment] 2024-02-02 17:36
> @e39a562r's patch works.

How to apply the patch
Gone through @e39a562r's patch thread, but do not know where and how to apply it.
Could you please show?

**Comment by ShionArtist** [comment] 2024-02-02 17:40
> > @e39a562r's patch works.
> 
> How to apply the patch Gone through @e39a562r's patch thread, but do not know where and how to apply it. Could you please show?

 download the .js file and then drag ot to the browser, greasemonkey should show a reinstall. ithe patch works^^

**Comment by 4as** [comment] 2024-02-02 20:25
For people who are using @e39a562r patch please confirm whether it works correctly on Android and iOS too. If it does then I'll officially pull into the main release of DeMod.

**Comment by OMGitsMatt45** [comment] 2024-02-02 21:28
I mean it works, but it doesn't show flagged or rejected notifications next to the DeMod on or off button

**Comment by e39a562r** [comment] 2024-02-03 13:38
Uhhh suddenly a lot of notifications. 🔔🔔🔔 

The bug currently not happening on my account so I can't test it. 
Somebody please help to test the patch on mobile devices. 🙏.
My patch is not good, users have to manually refresh the page after ChatGPT finish generating, but feel free to use/include it. 👍👍👍

**Comment by Orangestar12** [comment] 2024-02-03 18:59
Yeah, the patch is definitely a stopgap rather than a true solution. Sometimes generations inside long chats stop midway through—not, like, stop streaming, but stop generating altogether. A refresh proves that the generation didnt finish. No clue what's causing that one.

**Comment by OMGitsMatt45** [comment] 2024-02-05 21:28
I think it's back to normal again

**Comment by OMGitsMatt45** [comment] 2024-02-06 17:49
nope, nevermind

**Comment by OMGitsMatt45** [comment] 2024-02-06 17:58
I'm getting this in my console. 
![Screenshot (231)](https://github.com/4as/ChatGPT-DeMod/assets/111210801/1d988a5e-5b66-40bc-92ad-2f92b3063464)

**Comment by OMGitsMatt45** [comment] 2024-02-06 18:36
So it turns out they're doing a slow roll out or A/B testing

**Comment by OMGitsMatt45** [comment] 2024-02-09 16:59
Are we in the clear now?

**Comment by OMGitsMatt45** [comment] 2024-02-13 02:22
Nevermind...guess what's back

**Comment by etherealxx** [comment] 2024-02-14 11:03
Happened to me again just now, just this afternoon i guess, very recent. When you refresh the page, then output is displayed there, but you need to refresh everytime

**Comment by OMGitsMatt45** [comment] 2024-02-15 17:56
Is anyone getting stuff past moderation with the error?

**Comment by etherealxx** [comment] 2024-02-15 22:29
> Happened to me again just now, just this afternoon i guess, very recent. When you refresh the page, then output is displayed there, but you need to refresh everytime

Found out that the bug only happened on desktop for some reason? On mobile the DeMod works just fine. On Desktop, if you open inspect element and use mobile mode, it will also runs fine

**Comment by 99lorenzospina** [comment] 2024-02-16 00:30
![immagine](https://github.com/4as/ChatGPT-DeMod/assets/87083237/a5a5ec8a-941a-4a17-87b2-274f4a2ebd04)

Hello everyone, I'm having this similar error. Works only with refreshing.

**Comment by TrollMasterr** [comment] 2024-02-18 07:46
thanks etherealxx yea just installing extension "User-Agent Switcher for Chrome" even on edge and choosing "android" in options fixes the issue completely

**Comment by 4as** [comment] 2024-02-25 23:47
Can anyone confirm for me if this issue still exists with the latest version of DeMod 4.0?

**Comment by ZarkoSSR** [comment] 2024-02-26 03:22
> Can anyone confirm for me if this issue still exists with the latest version of DeMod 4.0?

It works for me now. I had the error constantly on computer for a while and this update has solved it. Thank you for your hard work, this has done wonders for me!

**Comment by etherealxx** [comment] 2024-02-26 03:30
> Can anyone confirm for me if this issue still exists with the latest version of DeMod 4.0?

The fix worked for me too, the issue is now nonexistent. Thanks for spending time fixing the bug, a lot of people using this extension. Great work🙏

**Closed** 2024-02-26 08:39 UTC
